name: project_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  flutter_login: ^4.1.1
  provider: ^6.0.5
  material_design_icons_flutter: ^6.0.7096
  floor: ^1.4.2
  http: ^0.13.6
  jwt_decoder: ^2.0.1
  intl: ^0.18.1
  sqlite3: ^1.11.2
  fl_animated_linechart: ^1.1.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2
  

flutter:
  uses-material-design: true
  assets:
      - assets/images/fitbit.png
      - assets/images/yalla.png
      - assets/images/cat.png
      - assets/images/walking.png
      - assets/images/heart.png
      
